version: "3.7"

services:

  postgres:
    container_name: fastapi_postgres
    image: postgres:14.5-alpine
    env_file:
      - .env
    shm_size: 64M
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/psql_init.sh:/docker-entrypoint-initdb.d/postgres-init.sh
    restart: always
    ports:
      - "${POSTGRES_PORT:-5432}:5432"

volumes:
  postgres_data:
